name = "la-dev"
compatibility_date = "2024-02-28"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[[d1_databases]]
binding = "DB"
database_name = "la-dev-db"
database_id = "81476d9d-7cc6-452c-a161-ec9171a2977f"
